config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  match 'user_login', to: 'home#user_login', via: [:get, :post]
  match 'analytics', to: 'home#analytics', via: [:get]

  resources :users

  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/timesheet.rb
class Timesheet < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :timesheets

	validates :username, presence: true, format: {with: /\A[a-zA-Z0-9_]*\z/, message: "The user name should be of one word. It should not include spaces, special characters."}
	validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def user_login
  	if params[:username].present?
  	  user = User.find_by_username(params[:username])
  	  if user.present?
	  	  if user.timesheets.present? && user.timesheets.where("DATE(entry_time) = ?", Date.today)
  	  		flash[:error] = "You have already filled the timesheet for today."
	  	  else
	  	  	timesheet = user.timesheets.build
	  	  	timesheet.entry_time = Time.zone.now
	  	  	puts timesheet.entry_time
	  	  	timesheet.save
	  	  	puts timesheet
	  	  	if timesheet.entry_time.strftime('%H:%M') > "10:00"
	  	  	  flash[:error] = "You are late!! Logged in at #{timesheet.entry_time.strftime('%d-%m-%Y %H:%M')}"
	  	    else	
	  	  	  flash[:notice] = "Successfully logged in at #{timesheet.entry_time.strftime('%d-%m-%Y %H:%M')}"
	  	  	end  
	  	  end	
	  else
		flash[:notice] = "No such User"	  
	  end
	else
		flash[:error] = "Please enter User Name to login"
  	end
  	redirect_to home_index_path
  end

  def analytics
  	@users_today = Timesheet.where("DATE(entry_time) = ?", Date.today)
  	@average_time = nil
  	if @users_today.present?
  		total_times = @users_today.map{|x| x.entry_time.strftime('%H:%M').to_time.to_i}
  		avg_time = Time.at(total_times.inject(:+)/@users_today.count)
  		@average_time = avg_time.strftime('%H:%M')
  	end	
  end	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @average_time = nil
    if @user.present?
      total_times = @user.timesheets.map{|x| x.entry_time.strftime('%H:%M').to_time.to_i}
      avg_time = Time.at(total_times.inject(:+)/@user.timesheets.count)
      @average_time = avg_time.strftime('%H:%M')
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to home_index_path, notice: 'User Name was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/analytics.html.erb
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Username</th>
      <th>Arrival Date</th>
      <th>Arrival Time</th>
    </tr>
  </thead>

  <tbody>
    <% @users_today.each do |timesheet| %>
      <tr>
        <td><%= link_to timesheet.user.username, user_path(timesheet.user_id), style: "color: blue;" %></td>
        <td><%= timesheet.entry_time.strftime('%d-%m-%Y') %></td>
        <td><%= timesheet.entry_time.strftime('%H:%M') %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="2"><strong>Average</strong></td>
      <td><strong><%= @average_time %></strong></td>
    </tr>
  </tfoot>
</table>

app/views/home/index.html.erb
<div class="col-md-6">
	<div class="panel panel-default">
	  <div class="panel-heading">Log in</div>
	  <div class="panel-body">
	  	<%= form_tag(user_login_path) do %>
	  	  <div class="form-group">
		    <label>User Name</label>
		    <%= text_field_tag :username, '', class: "form-control" %>
	      </div>
		  <div class="clearfix"></div>

		  <div class="form-group">
		    <%= submit_tag "Create User Name", class: "btn btn-primary float-right" %>
		  </div>
	  	<% end %>
	  </div>
	</div>
</div>

<div class="col-md-6">
	<div class="panel panel-default">
	  <div class="panel-heading">Create your User Name</div>
	  <div class="panel-body">
		<%= link_to "Create User", new_user_path, type: 'button', class: "btn btn-primary btn-lg btn-block" %>
	  </div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <nav class="navbar navbar-default">
	<div class="container-fluid">
	  <div class="navbar-header">
	    <a class="navbar-brand" href="<%= root_path %>">
	      Tracking System
	    </a>
	    <ul class="nav navbar-nav">
	        <li class="active">
	        	<%= link_to 'Analytics', analytics_path %>
	        </li>
	      </ul>
	  </div>
	</div>
  </nav>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if notice %>
		<div class="alert alert-success col-md-8 col-md-offset-2" style="margin-top: 10px;" role="alert">
		  <%= notice %>
		</div>
	<% end %>
	<% if flash[:error] %>
		<div class="alert alert-warning col-md-8 col-md-offset-2" style="margin-top: 10px;" role="alert">
		  <%= flash[:error] %>
		</div>
	<% end %>

	<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<div class="panel-body">
  <%= form_for(user) do |f| %>
    <% if user.errors.any? %>
      <% user.errors.full_messages.each do |message| %>
        <div class="alert alert-danger col-md-8 col-md-offset-2" role="alert">
          <%= message %>
        </div>
      <% end %>
    <% end %>
    <div class="clearfix"></div>

    <div class="form-group col-md-6">
      <%= f.label :username %>
      <%= f.text_field :username, class: "form-control" %>
    </div>
    <div class="clearfix"></div>

    <div class="form-group col-md-6">
    <%= f.submit "Create User Name", class: "btn btn-primary float-right" %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Create new User Name</h3>
  </div>
  <%= render 'form', user: @user %>
<div>

app/views/users/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">User Name : <%= @user.username %>
    	<%= link_to 'Back', analytics_path, class: "pull-right btn btn-default" %>
    </h3>
    <div class="clearfix"></div>
  </div>
  <div class="panel-body">
    <table class="table table-bordered table-striped">
	  <thead>
	    <tr>
	      <th>Arrival Date</th>
	      <th>Arrival Time</th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @user.timesheets.each do |timesheet| %>
	      <tr>
	        <td><%= timesheet.entry_time.strftime('%d-%m-%Y') %></td>
	        <td><%= timesheet.entry_time.strftime('%H:%M') %></td>
	      </tr>
	    <% end %>
	  </tbody>
	  <tfoot>
	    <tr>
	      <td><strong>Average</strong></td>
	      <td><strong><%= @average_time %></strong></td>
	    </tr>
	  </tfoot>
	</table>
  </div>
</div>